# -*- coding: utf-8 -*-
"""6 nov 2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C6n0JbfXgqc4k3s0f_UtxJvKZEb5Scxb
"""

# user define function
def pr():
  print("Hi i am bringing a called by user define function pr")

pr()

#paramaterised function    ====  can accept the valu from user
#non-paramaterised function    ====  cann't accept the valu from user  
#==1


def pr(name):
  print(name +" cipher")
pr("Anurag")

#==2

def pr(name,age):
  print(name + age +" cipher")
pr("Anurag","30")

def pr(first_name, last_name):
  print(first_name + " " + last_name)
pr("Cipher" , "Schools")

#==2

def pr(*name):
  print("My name is " + name[1] + "" + name[3]+ name[0]  )
pr("Anurag","Cipher ","Schools ","Shlok ")

def pr(name1 , name2, name3):
  print("My name is " + name3)
pr(name1= "anurag",name2="cipher",name3="schools")

def pr(name):
  for i in name:
   print(name)
name=["Anurag" , "Cipher" ,"Schools"]
pr(name)

def pr(n):
  return 5*n
pr(9)

# recursion on factorial
def factorial(n):
  if n==1:
    return 1
  else:
    return (n * factorial(n-1))
factorial(6)    

# firstly unbinding the values
#

def factorial(n):
  if n==1:
    return 1
  else:
    return(n*factorial(n-1))
factorial(5)

def factorial(n):
  if n==1:
    return 1
  else:
    return(n*factorial(n-1))
factorial(5)

def sum(n):
  if n==1:
    return n
  else:
    return n + sum(n-1)
sum(5)

